const MOCK_DATA = [
    {
        id: 1,
        nombre: "Akira 3",
        precio: 5900,
        editorial: "OvniPress",
        img: "public/img/akira3.png",
        stock: 1
    },
    {
        id: 2,
        nombre: "Attack On Titan 33",
        precio: 1900,
        editorial: "OvniPress",
        img: "public/img/attack33.png",
        stock: 1
    },
    {
        id: 3,
        nombre: "Basilisk 1",
        precio: 2000,
        editorial: "IVREA",
        img: "public/img/basilisk1.png",
        stock: 1
    },
    {
        id: 4,
        nombre: "Berserk 21",
        precio: 2200,
        editorial: "Panini",
        img: "public/img/berserk21.png",
        stock: 1
    },
    {
        id: 5,
        nombre: "Blue Lock 12",
        precio: 1800,
        editorial: "IVREA",
        img: "public/img/blue12.png",
        stock: 1
    },
    {
        id: 6,
        nombre: "Dragon Ball CSF: 3",
        precio: 3900,
        editorial: "IVREA",
        img: "public/img/dragonballcolorf3.png",
        stock: 1
    },
    {
        id: 7,
        nombre: "Fire Force 16",
        precio: 1700,
        editorial: "Panini",
        img: "public/img/fireforce16.png",
        stock: 1
    },
    {
        id: 8,
        nombre: "Hiraet 3",
        precio: 2000,
        editorial: "Distrito",
        img: "public/img/hiraet3.png",
        stock: 1
    },
    {
        id: 9,
        nombre: "Joy 1",
        precio: 2000,
        editorial: "Distrito",
        img: "public/img/joy1.png",
        stock: 1
    },
    {
        id: 10,
        nombre: "Jujutsu Kaisen 4",
        precio: 2100,
        editorial: "Panini",
        img: "public/img/jujutsukaisen4.png",
        stock: 1
    },
    {
        id: 11,
        nombre: "Kieta Hatsukoi 3",
        precio: 2100,
        editorial: "Panini",
        img: "public/img/kietahatsukoi3.png",
        stock: 1
    },
    {
        id: 12,
        nombre: "Kingdom 8",
        precio: 2200,
        editorial: "IVREA",
        img: "public/img/kingdom8.png",
        stock: 1
    },
    {
        id: 13,
        nombre: "My Hero 36",
        precio: 1800,
        editorial: "IVREA",
        img: "public/img/myhero36.png",
        stock: 1
    },
    {
        id: 14,
        nombre: "Noragami 21",
        precio: 1700,
        editorial: "Panini",
        img: "public/img/noragami21.png",
        stock: 1
    },
    {
        id: 15,
        nombre: "One Punch-Man 25",
        precio: 1500,
        editorial: "Panini",
        img: "public/img/onepunch25.png",
        stock: 1
    },
    {
        id: 16,
        nombre: "Orient 1",
        precio: 1900,
        editorial: "OvniPress",
        img: "public/img/orient1.png",
        stock: 1
    },
    {
        id: 17,
        nombre: "Saint Seiya 1",
        precio: 4200,
        editorial: "IVREA",
        img: "public/img/saintseiya1.png",
        stock: 1
    },
    {
        id: 18,
        nombre: "Shikimori 3",
        precio: 2000,
        editorial: "Distrito",
        img: "public/img/shikimori3.png",
        stock: 1
    },
    {
        id: 19,
        nombre: "Soul Eater 18",
        precio: 2900,
        editorial: "OvniPress",
        img: "public/img/souleater18.png",
        stock: 1
    },
    {
        id: 20,
        nombre: "Vinlad Saga 1",
        precio: 2650,
        editorial: "OvniPress",
        img: "public/img/vinland1.png",
        stock: 1
    },
    {
        id: 21,
        nombre: "Yu-Gi-Oh! 14",
        precio: 2800,
        editorial: "Panini",
        img: "public/img/yugi14.png",
        stock: 1
    }
]

export default MOCK_DATA